name: AI.defender
on: Android 10 LM-K500UM
  push:
  
    branches: [  ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew build
- name: Fortify on Demand Scan
  uses: fortify/gha-setup-fod-uploader@v1.0.1
  
  - name: Setup Node
  uses: actions/setup-node@v1
  with:
    node-version: '10.x'
    
    - name: Install Dependencies
  run: npm install
  
obs:
  test:
    name: Test on node ${{ matrix.node_version }} and ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node_version: ['8', '10', '12']
        os: [ubuntu-latest, windows-latest, macOS-latest]

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node_version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node_version }}

    - name: npm install, build and test
      run: |
        npm install
        npm run build --if-present
        npm test
        
        steps:
- run: npm publish
  if: github.event == 'push'}}
  
  
